version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: bitnami/elasticsearch:8
    container_name: elasticsearch
    environment:
      - ELASTICSEARCH_ENABLE_SECURITY=false
      - ELASTICSEARCH_HEAP_SIZE=1024m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/bitnami/elasticsearch

  logstash:
    image: bitnami/logstash:8
    container_name: logstash
    ports:
      - "5000:5000"
    environment:
      - LOGSTASH_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./logstash/pipeline:/bitnami/logstash/pipeline
    depends_on:
      - elasticsearch
      - redis

  kibana:
    image: bitnami/kibana:8
    container_name: kibana
    environment:
      - KIBANA_ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata: